language: python

os:
    - linux

branches:
  only:
    - master

addons:
  apt:
    packages:
      - python
      - gcc
      - gdb
      - python-pip


before_script:
  - echo $HOME/$TRAVIS_REPO_SLUG/gef.py > ~/.gdbinit

script:
  - gdb -ex 'gef help' -ex 'gef config' /bin/ls

after_script:
  - $HOME/$TRAVIS_REPO_SLUG/tests-runner.py

notifications:
  email:
    recipients:
      - hugsy+github@blah.cat

    on_success: change
    on_failure: always
